language: python
before_install:
- pip install pycodestyle
- pip install pytest
- pip install pytest-cov
- pip install coveralls
- pip install sphinx
- pip install sphinx_rtd_theme
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: gdwROQFvCcBMtPCokgN/VRkOolQTTqhLGXbwPd9rp4RZigtM0DtR3jAXg9JlJw8zutTIfdfTcuPqKkmphBzqXPN7Qkhr+eHXt4AVn4h5nm4YT+s8EMtAcKCHdNl3FtdICFMMaIyJfF4lHf5b4Qj8GGRRMJEvOH9wZsHo63IHe0DvvZEbJKByP35RTTTxXwEf46a/RWNTOZNfKtut7xAwdGBKytjFz3h8TI/zgg8Qk/Xb6L4uxDj7aMu6IdR3x7MMxXGqAHtEyxIqhcrGhA4r+K+DWKBz38VXUIY9HGDhGKbYRyX3zOkqBPgjtGtFO+ybjgAKMKGrPN/pWeQKPMjCq3/mQOouJGNlfS85I4AUiWA+NqmNtferrgSgwrOx/JM4Mji6NSJ/ppIMyn5EEBKjbYTsRCSR3SahM31OalPqaX5aZNtaNgwCWFunwerSjreoZi2rIFeVIymBg0B2m9vtY5QyVe1UJaUzf/XtXQu0ORJpwE57D5x5MkP0/81izKFujCTfL+HJmj73nDLWuugdBPmlccD8u1LhkUUsg2XFtviZL02R16MEDKg+tXarNflgLJrtwAQ/2Tq5rOdFCYF5B6rmIvmUKB66JqQRzyOkPQFmyp3IEjGLI0Q2b1N3hti6E3Br4a873dXqVMUgiSId0JFkjqIXr9UZ8LXS1xdvfUY=
    on:
      branch: master
      tags: true